### ISSUE TITLE
Mangel an UwU-Faktor in TetrisFX

### ISSUE THREAD

**Issue by lukaswittmann** [babkhdtsjn/TetrisFX#1]
Ich möchte gerne darauf hinweisen, dass ich beim Spielen von TetrisFX einen Mangel an UwU-Faktor festgestellt habe. Als Fan des Spiels würde ich es lieben, wenn das Spielerlebnis ein wenig mehr Flauschigkeit und Niedlichkeit hätte.

Konkret würde ich vorschlagen:

- Niedliche Grafiken: Können wir vielleicht die Grafiken etwas knuddeliger gestalten? Vielleicht niedliche Tiere oder süße Symbole für die Tetris-Blöcke?
- UwU-Soundeffekte: Wie wäre es mit einigen liebenswerten Geräuschen, wenn Blöcke platziert werden oder Linien verschwinden? Ein wenig mehr "UwU" in den Soundeffekten könnte das Spielerlebnis wirklich aufwerten.
- UwU-Modus: Vielleicht könnten wir einen speziellen "UwU-Modus" hinzufügen, der das Spiel noch herzerwärmender macht? Dies könnte eine Option sein, die die Grafiken und Soundeffekte entsprechend anpasst.

Ich glaube, dass diese Änderungen TetrisFX zu einem noch unterhaltsameren Spiel für eine breitere Zielgruppe machen könnten, insbesondere für diejenigen, die sich nach etwas mehr Flauschigkeit in ihrem Leben sehnen.

**Comment by Albkat** [comment]
![grafik](https://github.com/babkhdtsjn/TetrisFX/assets/92109627/92778832-7c6c-48e1-ae33-a505fcf26b70)

**Comment by lukaswittmann** [comment]
Thanks @Albkat for your input! Maybe @gasevic has some insight also?

![Alt Text](https://i.giphy.com/May0SdjFNSrckK7LO9.webp)

**Comment by Albkat** [comment]
<img src="https://tenor.com/de/view/cute-cat-uwu-dance-hearts-gif-20509166.gif" width="100">

**Comment by babkhdtsjn** [comment]
Es tut mir leid, das zu hören Herr Wittmann. TetrisFX ist ein abgeschlossenes Projekt und momentan nicht mein Hauptfokus. Ich werde versuchen, Ihre Vorschläge in meinem nächsten Projekt zu berücksichtigen.
